// Stamped into the bundle when the build runs, so the Settings footer can say
// which build a player is looking at alongside the version number. Read through
// `src/utils/buildInfo.ts`; `next dev` re-reads it every time the dev server
// restarts.
const buildTime = new Date().toISOString();

/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_BUILD_TIME: buildTime,
  },
  // Source maps are off in every flavour, because we were paying for them by
  // the deployment rather than by the bug. They are build output, so Vercel
  // stores a fresh copy of the lot for every deployment it retains, and at ten
  // merges a day that is the single biggest line in the storage bill: the
  // browser maps alone came to 13MB against 2.7MB of the JS they describe, the
  // server maps to another 35MB, and turning all three off takes a build from
  // 75MB to 25MB. Nothing a player downloads changes either way — a browser
  // only fetches a `.map` with devtools already open, and nothing ever fetches
  // the server ones.
  //
  // The cost is unsymbolised stack traces: a runtime error in the Vercel log or
  // the browser console names a minified chunk rather than a file and line. To
  // read one, flip the relevant flag back on locally (or on a preview) and
  // reproduce it there rather than leaving them on in production.
  productionBrowserSourceMaps: false,
  experimental: {
    // Emits `.next/server/**/*.map`, and defaults to on.
    turbopackSourceMaps: false,
    serverSourceMaps: false,
  },
  images: {
    // Profile pictures Clerk holds for a user (today: the avatar their SSO
    // provider supplied). Anything else fails the optimiser and Avatar falls
    // back to its initials badge.
    remotePatterns: [{ protocol: 'https', hostname: 'img.clerk.com' }],
  },
  // Android fetches this exact path to decide whether the app may open
  // asyncgames.com links (see src/app/api/assetlinks/route.ts). The App Router
  // has no way to name a `.well-known` folder, so the well-known path is
  // rewritten onto a route that can.
  async rewrites() {
    return [{
      source: '/.well-known/assetlinks.json',
      destination: '/api/assetlinks',
    }];
  },
  // Everything under /icons is generated by `npm run icons` and only changes
  // when that is re-run and committed — including the per-game share cards a
  // join link unfurls to, which every crawler and every recipient of a shared
  // link fetches. Served from the CDN for a day rather than revalidated on
  // each request.
  async headers() {
    return [{
      source: '/icons/:file*',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=86400, stale-while-revalidate=604800' }],
    }];
  },
};

export default nextConfig;
