/** @type {import('next').NextConfig} */
const nextConfig = {
  swcMinify: false,
  productionBrowserSourceMaps: true,
  images: {
    // Profile pictures Clerk holds for a user (today: the avatar their SSO
    // provider supplied). Anything else fails the optimiser and Avatar falls
    // back to its initials badge.
    remotePatterns: [{ protocol: 'https', hostname: 'img.clerk.com' }],
  },
  // Everything under /icons is generated by `npm run icons` and only changes
  // when that is re-run and committed — including the per-game share cards a
  // join link unfurls to, which every crawler and every recipient of a shared
  // link fetches. Served from the CDN for a day rather than revalidated on
  // each request.
  async headers() {
    return [{
      source: '/icons/:file*',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=86400, stale-while-revalidate=604800' }],
    }];
  },
};

export default nextConfig;
